services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: romain
      POSTGRES_PASSWORD: votre_mot_de_passe
      POSTGRES_DB: databasestudymove
    ports:
      - '5432:5432'
    networks:
      - studymovenetwork

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: romain
      DB_PASSWORD: votre_mot_de_passe
      DB_NAME: databasestudymove
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - studymovenetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - studymovenetwork

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - '3000:80'
  #   depends_on:
  #     - backend
  #   networks:
  #     - studymovenetwork

networks:
  studymovenetwork:
    driver: bridge
